import { describe, expect, it } from 'vitest';
import {
  activeLocationTimeSlots,
  normalizeLocationTimeSlots,
} from '../../services/locationTimeSlotService';

const timeSlot = {
  weekday: 'friday' as const,
  startTime: '19:00',
  endTime: '21:30',
  active: true,
  guestPlayEnabled: true,
};

describe('Location time-slot service', () => {
  it('generates an opaque id for a new slot and preserves an existing id on edit', () => {
    const [created] = normalizeLocationTimeSlots([timeSlot]);
    const [updated] = normalizeLocationTimeSlots(
      [{ ...timeSlot, id: created.id, endTime: '22:00' }],
      new Set([created.id])
    );

    expect(created.id).toMatch(/^[0-9a-f-]{36}$/);
    expect(updated).toMatchObject({ id: created.id, endTime: '22:00' });
  });

  it('defaults missing Guest Play availability to allowed and preserves a restriction', () => {
    const { guestPlayEnabled: _ignored, ...withoutGuestPlaySetting } = timeSlot;

    expect(
      normalizeLocationTimeSlots([withoutGuestPlaySetting])[0].guestPlayEnabled
    ).toBe(true);
    expect(
      normalizeLocationTimeSlots([{ ...timeSlot, guestPlayEnabled: false }])[0]
        .guestPlayEnabled
    ).toBe(false);
  });

  it('rejects client-selected ids and filters inactive slots for active projections', () => {
    expect(() =>
      normalizeLocationTimeSlots([
        { ...timeSlot, id: '0a0a0a0a-0000-4000-8000-000000000001' },
      ])
    ).toThrow('generated by the server');

    const active = normalizeLocationTimeSlots([timeSlot])[0];
    const inactive = { ...active, id: 'inactive', active: false };
    expect(activeLocationTimeSlots([active, inactive])).toEqual([active]);
  });
});
