import { randomUUID } from 'node:crypto';
import type {
  LocationTimeSlot,
  LocationTimeSlotInput,
} from '@club/shared-types/api/location';
import { LOCATION_TASTER_SESSION_LEVELS } from '@club/shared-types/api/location';
import { AppError } from '../utils/errors';

export const normalizeLocationTimeSlots = (
  timeSlots: LocationTimeSlotInput[],
  existingIds: ReadonlySet<string> = new Set()
): LocationTimeSlot[] =>
  timeSlots.map((slot) => {
    if (slot.id && !existingIds.has(slot.id)) {
      throw new AppError('Time slot ids are generated by the server', 400);
    }

    return {
      ...slot,
      id: slot.id ?? randomUUID(),
      guestPlayEnabled: slot.guestPlayEnabled ?? true,
      tasterSessionEnabled: slot.tasterSessionEnabled ?? true,
      tasterSessionAcceptedLevels: slot.tasterSessionAcceptedLevels ?? [
        ...LOCATION_TASTER_SESSION_LEVELS,
      ],
      note:
        slot.note && Object.values(slot.note).some(Boolean)
          ? slot.note
          : undefined,
    };
  });

export const activeLocationTimeSlots = (
  timeSlots: LocationTimeSlot[]
): LocationTimeSlot[] => timeSlots.filter((slot) => slot.active);
